/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MemberDto } from '../../models/member-dto';

export interface ApiMembersPost$Json$Params {
      body?: MemberDto
}

export function apiMembersPost$Json(http: HttpClient, rootUrl: string, params?: ApiMembersPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<MemberDto>> {
  const rb = new RequestBuilder(rootUrl, apiMembersPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MemberDto>;
    })
  );
}

apiMembersPost$Json.PATH = '/api/Members';
