/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeeTypeDto } from '../models/fee-type-dto';
export interface FeeDto {
  amount: number;
  id?: string;
  isPaid?: boolean;
  memberId: string;
  paymentDate?: string | null;
  type: FeeTypeDto;
  year: number;
}
