/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MemberDto {
  address: string;
  bankAccount: string;
  birthDate?: string;
  dni: string;
  email: string;
  hasShare?: boolean;
  id?: string;
  isActive?: boolean;
  isIbercaja?: boolean;
  joinDate?: string;
  name: string;
  parentMemberId?: string | null;
  shareNumber?: number | null;
  surname: string;
}
